---
galaxy_info:
  author: mkbrechtel
  description: Configure the system Message of the Day (MOTD)
  company: mkbrechtel
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - motd
    - system
    - configuration

dependencies: []
