---

- name: home directory
  file:
    path: "{{ users[item].home | default('/home/'+item) }}"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: "{{ users[item].homedir_mode | default('u=rwx,g=rx,o=') }}"
    state: directory
  loop: "{{ users.keys() | list }}"
