---

- name: ssh key
  user:
    name: "{{ item }}"
    generate_ssh_key: yes
    ssh_key_type: ed25519
  register: user_ssh_keys_info
  loop: "{{ users.keys() | list }}"

- name: ssh directory
  file:
    path: "{{ users[item].home | default('/home/'+item) }}/.ssh"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: "0700"
    state: directory
  loop: "{{ users.keys() | list }}"

- name: ssh authorized keys
  template:
    src: ssh_authorized_keys.j2
    dest: "{{ users[item].home | default('/home/'+item) }}/.ssh/authorized_keys"
    owner: "{{ item }}"
    group: "{{ item }}"
  loop: "{{ users.keys() | list }}"
  when: users[item].ssh_authorized_keys is defined
